### PR TITLE
ReactiveSocket d'tor can be called from signal handler of a stream.

### PR DESCRIPTION
**Pull request by stupaq-fb**
DO NOT MERGE!

This is still a WIP, to do:
* write a test to verify it actually works
* provide stronger guarantees to DuplexConnection, so that it's easier to get right.

### CODE REVIEW

**Comment by stupaq-fb** [comment]
This fixes #34.

**Comment by stupaq-fb** [comment]
So far, I know that:
* it's safe, since we hold a strong reference to ConnectionAutomaton, i.e. we cannot possibly dereference dangling pointer/reference,
* ConnectionAutomaton doesn't hold strong references to AbstractStreamAutomata, so there is no leak there -- I actually verified that d'tor of ConnectionAutomaton is invoked,
* as a bonus, ConnectionAutomaton::endStream is still idempotent, which simplifies AbstractStreamAutomata.

**Comment by stupaq-fb** [comment]
GOOD TO MERGE (after review)

@yschimke, take a look at the test, please.

**Comment by yschimke** [comment]
The test makes sense to me, but and other changes all looked appropriate given the pointer changes.

**Pull request merged**
