### PR TITLE
Generate a www.gitignore.io .gitignore file

### PR DESCRIPTION
**Pull request by yschimke**
Had lots of files flagged by git after a build, so generating something sensible.

### CODE REVIEW

**Comment by stupaq-fb** [comment]
They are very much catch-all. I believe that using an off-source build would solve your problems entirely.

**Comment by yschimke** [comment]
That makes sense.  I believe I was following the README.md, is that something I should add there?

**Comment by stupaq-fb** [comment]
I'll update it. tl;dr CMake is flexible about location of the build dir (I've added /build to .gitignore initially, as that's what I've seen in other ptojects).

**Comment by stupaq-fb** [comment]
Sorry, did I just reject it? I wanted to merge it in, sorry.

**Pull request merged**
