### PR TITLE
Attempt Upgrade to gcc 4.9

### PR DESCRIPTION
**Pull request by benjchristensen**
Experimenting with Travis config.

### CODE REVIEW

**Comment by benjchristensen** [comment]
@lehecka This seems to work for gcc4.9, can you take a look? Do you want clang as well (which isn't working)?

**Comment by benjchristensen** [comment]
Seems like clang is just timing out ... and my attempt to extend the timeout failed :-/

**Comment by yschimke** [comment]
We unfortunately need support for both clang and gcc, as both are used internally.

**Comment by lehecka** [comment]
I know this is going to take a lot of tries to figure this out. Thank you for doing this!
I tried this and ended up convincing travis to use gcc 4.9, but the build was messed up enough that the tests froze and never completed: https://github.com/lehecka/reactivesocket-cpp/commit/17a592c7d4ed3ab11c97162325a633cdcdefc95d

**Comment by lehecka** [comment]
the latest attempt from me is here: https://travis-ci.org/lehecka/reactivesocket-cpp/builds/178380361

it looks like it all compiles, but gets stuck in executing tests.
Maybe we can disable tests and see if they are all messed up or just one test is messed up..

**Comment by lehecka** [comment]
closing in favor of https://github.com/ReactiveSocket/reactivesocket-cpp/pull/253

**Pull request closed without merging**
