### PR TITLE
remove deprecated MoveWrapper

### PR DESCRIPTION
**Pull request by yschimke**

### CODE REVIEW

**Comment by yschimke** [comment]
I believe we are blocked on c++14 support which requires changes to travisci

http://stackoverflow.com/questions/35110123/travis-ci-with-c14-and-linux
http://genbattle.bitbucket.org/blog/2016/01/17/c++-travis-ci/

and probably republishing our folly snapshot to bitbucket

**Comment by lexs** [comment]
What does Travis run? You can mostly use move in lambdas with `-std=gnu++1y` in GCC 4.8.

**Comment by yschimke** [comment]
I'll try that.  This was the error I got with -std=c++1y

```
In file included from /home/travis/build/ReactiveSocket/reactivesocket-cpp/src/AbstractStreamAutomaton.cpp:3:
In file included from /home/travis/build/ReactiveSocket/reactivesocket-cpp/src/AbstractStreamAutomaton.h:8:
In file included from /home/travis/build/ReactiveSocket/reactivesocket-cpp/src/Payload.h:5:
In file included from /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/memory:79:
In file included from /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/functional:55:
In file included from /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/tuple:39:
In file included from /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/array:38:
In file included from /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/stdexcept:39:
In file included from /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/string:52:
In file included from /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/basic_string.h:2815:
In file included from /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/ext/string_conversions.h:43:
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/cstdio:120:11: error: 
      no member named 'gets' in the global namespace
  using ::gets;
```

**Comment by yschimke** [comment]
@lexs nope, still busted https://travis-ci.org/ReactiveSocket/reactivesocket-cpp/jobs/167009539

**Comment by yschimke** [comment]
I'll come back to this in next few days and bump to c++14 via the travis update instructions I linked to so we are on a consistent platform

**Comment by lexs** [comment]
@yschimke Yeah something is really weird on Travis, folly event detects a recent C++ version and opts to use `std::make_unique` but then it doesn't exist? :(

**Comment by stupaq-fb** [comment]
Did you guys verify the folly release in Homebrew actually picked up quite recent change to Executor::add, which allows the method to take folly::Function?

**Comment by yschimke** [comment]
Good point, nope, not there yesterday.

```
$ grep Func /usr/local/Cellar/folly/2016.09.05.00_1/include/folly/Executor.h
typedef std::function<void()> Func;
  virtual void add(Func) = 0;
  virtual void addWithPriority(Func, int8_t /*priority*/) {
```

**Comment by yschimke** [comment]
homebrew now has this latest change

**Comment by yschimke** [comment]
too far out of date

**Pull request closed without merging**
