### PR TITLE
c++14

### PR DESCRIPTION
**Pull request by yschimke**
discuss!

### CODE REVIEW

**Comment by yschimke** [comment]
Travis doesn't seem to support this without additional steps, so I'll look into that unless someone else knows the story?

**Comment by yschimke** [comment]
or alternatively that we don't want this

**Comment by lehecka** [comment]
please check if fbandroid and fbobjc support c++14 before you turn this switch on. Last time I checked (4 months back) fb android didn't support it. It would be extra work to deal with the compile time issues for all new c++14 stuff.

**Comment by yschimke** [comment]
@lehecka stop suggesting std:make_unique then!

**Comment by lehecka** [comment]
sorry, I might have forgotten...
there is also folly::make_unique doing the same thing in C++11.

Maybe I'll just shutup..

**Pull request closed without merging**
