### PR TITLE
pull in change to leak the FrameAllocator

### PR DESCRIPTION
**Pull request by yschimke**
Leak the FrameAllocator to avoid shutdown destructor races

cc @lehecka @jspahrsummers

### CODE REVIEW

**Comment by lehecka** [comment]
I don't think this is a good change.
Why would you generate frames when the application is being teared down? If there is a timing issue in shutting down threads, it should be resolved somewhere else.

Lets open this issues and discuss it better. I feel there should be a better fix for the issue than this.

**Comment by lehecka** [comment]
Not sure why ASAN doesn't complain here, but we are essentially making memory leaking detection very hard since we are leaking by design.
I would like to find a different fix for the original problem.
@yschimke can you share some details about the original problem?

**Comment by jspahrsummers** [comment]
Will follow up on chat.

**Comment by yschimke** [comment]
I wanted to keep the two repos, in sync.  no objection to a more appropriate change.

**Pull request merged**
