### PR TITLE
Add basic unit tests for TcpDuplexConnection

### PR DESCRIPTION
**Pull request by foghina**
Not sure this is enough to close out #121, but it's a start.

### CODE REVIEW

**Comment by foghina** [comment]
Looks like folly needs to be updated in `reactivesocket-cpp-dependencies`.

**Comment by yschimke** [comment]
Leave this here, we need a fresh build of homebrew folly.  Once that is available, I'll be more keen to update the travis version also.

**Comment by foghina** [comment]
I'm using the latest homebrew folly, and it seems fresher than whatever travis has (i.e. this test passes). Or are you waiting for an even newer version?

**Comment by yschimke** [comment]
I'm looking for a fresher version, e.g. about 3 days old.

**Comment by benjchristensen** [comment]
@foghina thanks for getting involved and contributing!

**Comment by lehecka** [comment]
as there is no progress on this. I will close this PR.

**Pull request closed without merging**
