### PR TITLE
fixing formatting by running devtools/format_all.sh

### PR DESCRIPTION
**Pull request by lehecka**
I am planning on merging this PR right away since this is no more than formatting.

### CODE REVIEW

**Comment by lehecka** [comment]
how do we get on the same page with the tooling? Will try to update clang-format

**Comment by lehecka** [comment]
clang-format 2016-03-29 already installed

**Comment by yschimke** [comment]
```
$ clang-format --version
clang-format version 4.0.0 (tags/google/testing/2016-08-03)
```

**Comment by tmontgomery** [comment]
`brew` has the same version.

```
$ clang-format --version
clang-format version 4.0.0 (tags/google/testing/2016-08-03)
```

**Pull request merged**
