### PR TITLE
Travis Build

### PR DESCRIPTION
**Pull request by benjchristensen**
Continuous builds on Travis CI

- this pulls a pre-compiled version of folly from Bitbucket: https://bitbucket.org/reactivesocket/reactivesocket-cpp-dependencies/src
- it updates libs via apt-get
- it builds reactivesocket-cpp
- it runs ./ReactiveSocketTest

### CODE REVIEW

**Comment by benjchristensen** [comment]
Note that I have not yet tested whether it correctly shows as "failed" if a unit test fails. I'm assuming ./ReactiveSocketTest will return a value other than 0 and thus fail the build.

**Comment by stupaq-fb** [comment]
Yep, I believe it to be the case.

Could you update `make` command to `make -j8` or something? It seems that build is slow because of that.

**Comment by benjchristensen** [comment]
This pull request successfully shows how Travis does the build and shows as "green". The log can be seen here: https://travis-ci.org/ReactiveSocket/reactivesocket-cpp/builds/131003661

**Comment by benjchristensen** [comment]
men4a

Yak shaved.

**Comment by stupaq-fb** [comment]
Great!

**Comment by benjchristensen** [comment]
Build time with `make`: 1 minutes 43 seconds
Build time with `make -j8`: 1 minute 42 seconds
Build time without precompiled folly: > 10 minutes

**Comment by stupaq-fb** [comment]
#12 will speed things up, assuming we actually have multiple cores to build (I don't know how big the container is).

**Pull request merged**
